### ISSUE TITLE
Error in effort correction!

### ISSUE THREAD

**Issue by AdamCSmithCWS** [AdamCSmithCWS/CBC_Spatial_Modeling#1]
@tmeeha . We are getting strange effort corrections because I had left out the effort term from the main likelihood statement. So it was only drawing from the priors. 
Sorry.

**Comment by AdamCSmithCWS** [comment]
I've fixed this in the most recent commit.
In that same commit, I added a non-spatial effort version of the model, and I added a parameter to track the effort correction in each stratum.

**Comment by tmeeha** [comment]
Excellent! Thanks!

**Comment by tmeeha** [comment]
Excellent, thanks!
